# Generated by Django 4.1.5 on 2023-01-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='comision',
            field=models.IntegerField(default=0),
        ),
    ]
