# Generated by Django 4.1.5 on 2023-02-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_estudiante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='identificacion',
            field=models.IntegerField(default=0),
        ),
    ]
