# Generated by Django 4.1.5 on 2023-02-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_profesor_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='identificacion',
            field=models.IntegerField(default=0),
        ),
    ]
